export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_COMPARISON = "ADD_TO_COMPARISON";
export const INCREASE_TOTALPRICE = "INCREASE_TOTALPRICE";
export const DECREASE_TOTALPRICE = "DECREASE_TOTALPRICE";

